# Generated by Django 4.2 on 2023-05-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_device_alter_cart_user_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='device',
        ),
        migrations.AddField(
            model_name='cart',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
