# Generated by Django 4.2 on 2023-05-20 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_address_country_alter_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_address', to='accounts.cart'),
        ),
    ]
