# Generated by Django 4.2 on 2023-05-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='couon_code',
            new_name='coupon_code',
        ),
    ]
